export { default as AS } from './AS.svg'; // Ace of Spades
export { default as KS } from './KS.svg'; // King of Spades
export { default as QS } from './QS.svg'; // Queen of Spades
export { default as JS } from './JS.svg'; // Jack of Spades
export { default as TS } from './TS.svg'; // 10 of Spades
export { default as _9S } from './9S.svg'; // 9 of Spades
export { default as _8S } from './8S.svg'; // 8 of Spades
export { default as _7S } from './7S.svg'; // 7 of Spades
export { default as _6S } from './6S.svg'; // 6 of Spades
export { default as _5S } from './5S.svg'; // 5 of Spades
export { default as _4S } from './4S.svg'; // 4 of Spades
export { default as _3S } from './3S.svg'; // 3 of Spades
export { default as _2S } from './2S.svg'; // 2 of Spades

export { default as AH } from './AH.svg'; // Ace of Hearts
export { default as KH } from './KH.svg'; // King of Hearts
export { default as QH } from './QH.svg'; // Queen of Hearts
export { default as JH } from './JH.svg'; // Jack of Hearts
export { default as TH } from './TH.svg'; // 10 of Hearts
export { default as _9H } from './9H.svg'; // 9 of Hearts
export { default as _8H } from './8H.svg'; // 8 of Hearts
export { default as _7H } from './7H.svg'; // 7 of Hearts
export { default as _6H } from './6H.svg'; // 6 of Hearts
export { default as _5H } from './5H.svg'; // 5 of Hearts
export { default as _4H } from './4H.svg'; // 4 of Hearts
export { default as _3H } from './3H.svg'; // 3 of Hearts
export { default as _2H } from './2H.svg'; // 2 of Hearts

export { default as AD } from './AD.svg'; // Ace of Diamonds
export { default as KD } from './KD.svg'; // King of Diamonds
export { default as QD } from './QD.svg'; // Queen of Diamonds
export { default as JD } from './JD.svg'; // Jack of Diamonds
export { default as TD } from './TD.svg'; // 10 of Diamonds
export { default as _9D } from './9D.svg'; // 9 of Diamonds
export { default as _8D } from './8D.svg'; // 8 of Diamonds
export { default as _7D } from './7D.svg'; // 7 of Diamonds
export { default as _6D } from './6D.svg'; // 6 of Diamonds
export { default as _5D } from './5D.svg'; // 5 of Diamonds
export { default as _4D } from './4D.svg'; // 4 of Diamonds
export { default as _3D } from './3D.svg'; // 3 of Diamonds
export { default as _2D } from './2D.svg'; // 2 of Diamonds

export { default as AC } from './AC.svg'; // Ace of Clubs
export { default as KC } from './KC.svg'; // King of Clubs
export { default as QC } from './QC.svg'; // Queen of Clubs
export { default as JC } from './JC.svg'; // Jack of Clubs
export { default as TC } from './TC.svg'; // 10 of Clubs
export { default as _9C } from './9C.svg'; // 9 of Clubs
export { default as _8C } from './8C.svg'; // 8 of Clubs
export { default as _7C } from './7C.svg'; // 7 of Clubs
export { default as _6C } from './6C.svg'; // 6 of Clubs
export { default as _5C } from './5C.svg'; // 5 of Clubs
export { default as _4C } from './4C.svg'; // 4 of Clubs
export { default as _3C } from './3C.svg'; // 3 of Clubs
export { default as _2C } from './2C.svg'; // 2 of Clubs