export { default as BAS } from './AS.svg'; // Ace of Spades
export { default as BKS } from './KS.svg'; // King of Spades
export { default as BQS } from './QS.svg'; // Queen of Spades
export { default as BJS } from './JS.svg'; // Jack of Spades
export { default as BTS } from './TS.svg'; // 10 of Spades
export { default as B_9S } from './9S.svg'; // 9 of Spades
export { default as B_8S } from './8S.svg'; // 8 of Spades
export { default as B_7S } from './7S.svg'; // 7 of Spades
export { default as B_6S } from './6S.svg'; // 6 of Spades
export { default as B_5S } from './5S.svg'; // 5 of Spades
export { default as B_4S } from './4S.svg'; // 4 of Spades
export { default as B_3S } from './3S.svg'; // 3 of Spades
export { default as B_2S } from './2S.svg'; // 2 of Spades

export { default as BAH } from './AH.svg'; // Ace of Hearts
export { default as BKH } from './KH.svg'; // King of Hearts
export { default as BQH } from './QH.svg'; // Queen of Hearts
export { default as BJH } from './JH.svg'; // Jack of Hearts
export { default as BTH } from './TH.svg'; // 10 of Hearts
export { default as B_9H } from './9H.svg'; // 9 of Hearts
export { default as B_8H } from './8H.svg'; // 8 of Hearts
export { default as B_7H } from './7H.svg'; // 7 of Hearts
export { default as B_6H } from './6H.svg'; // 6 of Hearts
export { default as B_5H } from './5H.svg'; // 5 of Hearts
export { default as B_4H } from './4H.svg'; // 4 of Hearts
export { default as B_3H } from './3H.svg'; // 3 of Hearts
export { default as B_2H } from './2H.svg'; // 2 of Hearts

export { default as BAD } from './AD.svg'; // Ace of Diamonds
export { default as BKD } from './KD.svg'; // King of Diamonds
export { default as BQD } from './QD.svg'; // Queen of Diamonds
export { default as BJD } from './JD.svg'; // Jack of Diamonds
export { default as BTD } from './TD.svg'; // 10 of Diamonds
export { default as B_9D } from './9D.svg'; // 9 of Diamonds
export { default as B_8D } from './8D.svg'; // 8 of Diamonds
export { default as B_7D } from './7D.svg'; // 7 of Diamonds
export { default as B_6D } from './6D.svg'; // 6 of Diamonds
export { default as B_5D } from './5D.svg'; // 5 of Diamonds
export { default as B_4D } from './4D.svg'; // 4 of Diamonds
export { default as B_3D } from './3D.svg'; // 3 of Diamonds
export { default as B_2D } from './2D.svg'; // 2 of Diamonds

export { default as BAC } from './AC.svg'; // Ace of Clubs
export { default as BKC } from './KC.svg'; // King of Clubs
export { default as BQC } from './QC.svg'; // Queen of Clubs
export { default as BJC } from './JC.svg'; // Jack of Clubs
export { default as BTC } from './TC.svg'; // 10 of Clubs
export { default as B_9C } from './9C.svg'; // 9 of Clubs
export { default as B_8C } from './8C.svg'; // 8 of Clubs
export { default as B_7C } from './7C.svg'; // 7 of Clubs
export { default as B_6C } from './6C.svg'; // 6 of Clubs
export { default as B_5C } from './5C.svg'; // 5 of Clubs
export { default as B_4C } from './4C.svg'; // 4 of Clubs
export { default as B_3C } from './3C.svg'; // 3 of Clubs
export { default as B_2C } from './2C.svg'; // 2 of Clubs